---

# skip OSS deploy

- name: "remove old dir: {{update_center_dist_dir}}/{{app_local_dir_name}}"
  file:
    path: "{{update_center_dist_dir}}/{{app_local_dir_name}}"
    state: absent

- name: "untar {{update_center_dist_dir}}/{{app_local_dir_name}}-tgz.tar.gz"
  unarchive:
    src: '{{update_center_dist_dir}}/{{app_local_dir_name}}-tgz.tar.gz'
    dest: "{{update_center_dist_dir}}"
    remote_src: yes

- name: "register shall_update_center"
  shell: "echo 1"
  register: shall_update_center
  ignore_errors: True
  tags: deploy

- name: "generate shell script build-update-center.sh to '{{update_center_dist_dir}}/{{app_local_dir_name}}'"
  template:
    src: "{{item.name}}.j2"
    dest: "{{update_center_dist_dir}}/{{app_local_dir_name}}/{{item.name}}"
    force: no
    mode: '0644'
  vars:
    skip_update_center: "{{shall_update_center is not defined}}"
  with_items:
    - {name: "build-update-center.sh"}

- name: "execute shell script build-update-center.sh in dir:{{update_center_dist_dir}}/{{app_local_dir_name}}"
  shell: 'sh ./build-update-center.sh'
  run_once: true
  args:
    chdir: "{{update_center_dist_dir}}/{{app_local_dir_name}}"

