---
# tasks file for index-builder
  - name: clear local temp dir
    file:
     path: /tmp/{{item}}
     state: absent
    with_items:
     - "tis-index-builder-yarn"
     - "tis-index-builder-yarn.tar.gz"
  
  - name: copy tis-index-builder package
    copy: src='{{tis_release_dir}}/tis-index-builder-yarn.tar.gz' dest=/tmp/

  - name: unzip tis-index-builder tar
    unarchive:
     src: /tmp/tis-index-builder-yarn.tar.gz
     dest: /tmp/
     remote_src: yes
 
  - name: 'mkdir {{sharelib_dir}}'
    file: path={{sharelib_dir}} state=directory
      
  - name: synchronize jars in tis-index-builder
    synchronize:
      src: /tmp/tis-index-builder-yarn/
      dest: "{{sharelib_dir}}"
      delete: yes
    delegate_to: "{{ inventory_hostname }}"
  - name: set owner
    file:
      path: "{{sharelib_dir}}"
      owner: "{{hadoop_user}}"
      group: "{{hadoop_group}}"
      recurse: yes

