---
# tasks file for download
- name: Create Tmp Dir
  file: 
   path: "{{tis_release_dir}}/{{tis_pkg_version}}"
   state: directory
 
- name: Download Release Package
  get_url:
    url: "{{ release_repository }}/{{ item.name }}"
    dest: "{{ tis_release_dir }}/{{ item.name }}"
    force: no
  when: item.when
  with_items:
    - {name: "{{tis_pkg_version}}/solr.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-assemble.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-collect.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-index-builder.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-scala-compiler-dependencies.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/web-start.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-collect.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/ng-tis.tar.gz", when: True}
    - {name: "{{tis_pkg_version}}/tis-incr.tar.gz", when: True}
    - {name: "tis-ibatis.tar.gz", when: True}
    - {name: "{{ java_gz_file_name }}", when: True}
    - {name: "{{ zk_gz_file_name }}", when: "{{ need_install_zookeeper }}" }
    - {name: "{{ hadoop_gz_file_name }}", when: "{{ need_install_hadoop }}" }
    - {name: "{{ spark_scala_gz_file_name }}", when: "{{ need_install_hadoop and need_install_spark }}" }
    - {name: "{{ spark_gz_file_name }}", when: "{{ need_install_hadoop and need_install_spark }}" }
    - {name: "{{ spark_tispark_jar_file_name }}", when: "{{ need_install_hadoop and need_install_spark and need_install_tispark }}" }
    - {name: "{{ spark_thriftserver_jar_file_name }}", when: "{{ need_install_hadoop and need_install_spark and need_install_spark_shuffle }}" }
