---
- name: build assemble
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: git pull
    git:
     repo: 'git@github.com:baisui1981/tis.git'
     dest: '/opt/data/tiscode/tis'
     version: "{{git_branch}}"
  
  - name: copy compile shell script
    copy: src=compile.sh dest=/opt/data/tiscode/tis mode=u+rwx

  - name: compile and package
    command: ./compile.sh {{runtime}} tis-assemble
    args:
     chdir: /opt/data/tiscode/tis

- name: synchronize tis-assemble
  hosts: assemble
  become: yes
  become_method: sudo
  tags: deploy
  tasks:
  - file:
     path: /opt/data/spring-boot
     owner: spring-boot
     state: directory
  - file:
     path: /opt/data/flume
     owner: spring-boot
     state: directory
  - name: deploy dir-hdfs20.tar
    #unarchive: src=/opt/data/tiscode/dir-hdfs20.tar dest=/opt/data/spring-boot owner=spring-boot
    synchronize:
       src: ./files/dir-hdfs20
       dest: /opt/data/spring-boot/
       delete: yes
  - name: copy tis-assemble 
    copy:
     src: /opt/data/tiscode/tis/{{item}}
     dest: /tmp/
    with_items:
     - "tis-assemble.tar.gz"
  - name: copy assemble.properties
    copy:
     src: /opt/data/tiscode/assemble/assemble.properties
     dest: /opt/data/spring-boot/
     force: no
  - name: delete history tar.gz
    file:
      path: /tmp/tis-assemble
      state: absent
  - name: untar
    unarchive:
      src: /tmp/tis-assemble.tar.gz
      dest: /tmp/
      remote_src: yes
  - name: install rsync
    yum:
      name: "{{packages}}"
    vars:
      packages:
      - rsync
      - java
  - name: synchroniz assemble
    synchronize:
       src: /tmp/tis-assemble/
       dest: /opt/app/spring-boot/tis-assemble
       delete: yes
       recursive: yes
    delegate_to: "{{ inventory_hostname }}"
  - name: copy config.properties
    template:
     src: template/{{item}}.j2
     dest: /opt/app/spring-boot/tis/conf/tis-web-config/{{item}}
    with_items:
     - "config.properties"
     - "hdfs-site.xml"
  - name: path owner set
    file:
     path: "{{item}}"
     owner: spring-boot
     group: spring-boot
     recurse: yes
    with_items:
     - "/opt/app/spring-boot/tis-assemble"
     - "/opt/data/spring-boot"
