- name: set host machine hosts file
  vars_files:
    - vars.yml
  hosts: localhost
  tasks:
  - user:
      name: root
      group: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      shell: /bin/bash
  - lineinfile:
      dest: /etc/hosts
      regexp: "^.*? {{ item }}$"
      line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
      state: present
      create: yes
    with_inventory_hostnames: all
