---

- name: compile tis src tar package
  vars_files:
   - vars.yml
  hosts: localhost      
  roles:
   - role: jdk
   - role: compile
  tags:
    - package

- name: make tis-incr docker image
  vars_prompt:
    - name: "docker_password"
      prompt: "docker repository password"
      private: yes
  vars_files:
    - vars.yml
  hosts: localhost
  roles:
    - role: tis-incr
  tags:
    - incr

- name: make ng-tis package
  vars_files:
    - vars.yml
  hosts: localhost
  roles:
    - role: ng-tis
  tags:
    - ng-tis
    
- import_playbook: install_struct.yml
  

