---
- name: build dumpcenter
  hosts: localhost
  tasks:
  - name: git pull
    git:
     repo: 'git@github.com:baisui1981/tis.git'
     dest: /opt/data/tiscode/tis
     version: "{{git_branch}}"
  
  - name: copy compile shell script
    copy: src=compile.sh dest=/opt/data/tiscode/tis mode=u+rwx

  - name: compile and package
    command: bash ./compile.sh {{runtime}} tis-index-builder
    args:
     chdir: /opt/data/tiscode/tis
     #removes: ./tsearcher-dumpcenter.tar.gz

- name: synchronize jars
  hosts: buildtask-worker
  become: yes
  become_method: sudo
  tags: deploy
  tasks:
  - name: clear local temp dir
    file:
     path: /tmp/{{item}}
     state: absent
    with_items:
     - "tis-index-builder"
     - "tis-index-builder.tar.gz"
  
  - name: copy tis-index-builder
    copy: src=/opt/data/tiscode/tis/tis-index-builder.tar.gz dest=/tmp/

  - name: unzip tis-index-builder tar
    unarchive:
     src: /tmp/tis-index-builder.tar.gz
     dest: /tmp/
     remote_src: yes
  - name: synchronize jars in tis-index-builder
    synchronize:
      src: /tmp/tis-index-builder/
      dest: /home/admin/terminator_builder/sharelib/indexbuilder7.6
      delete: yes
    delegate_to: "{{ inventory_hostname }}"
  - name: set owner
    file:
      path: /home/admin/terminator_builder/sharelib/indexbuilder7.6
      owner: admin
      recurse: yes
      group: admin
