---
- name: build dumpcenter
  hosts: localhost
  become: yes
  become_method: sudo
#  become_user: baisui
#  vars_prompt: 
#    - name: runtime
#      prompt: 'build env [daily,publish]:'
#      default: daily
#      private: no
  tasks:
  - name: git pull
    git:
     repo: 'git@github.com:baisui1981/tis.git'
     dest: /opt/data/tiscode/tis
     version: "{{git_branch}}"
  
  - name: copy compile shell script
    copy: src=compile.sh dest=/opt/data/tiscode/tis-mars

  - name: compile and package
    command: bash ./compile.sh {{runtime}} tsearcher-dumpcenter
    args:
     chdir: /opt/data/tiscode/tis-mars
     #removes: ./tsearcher-dumpcenter.tar.gz

- name: synchronize jars
  hosts: buildtask
  become: yes
  become_method: sudo
  #vars_prompt: 
  #  - name: hosts
  #    prompt: 'hosts you want to synchronize[tis-prod,tis-kr]:'
  #    default: localhost
  tags: deploy
  tasks:
  - name: copy tsearcher-dumpcenter.tar.gz
    copy: src=/opt/data/tiscode/tis-mars/tsearcher-dumpcenter.tar.gz dest=/tmp/
  - name: remove old file
    file:
     path: /tmp/tsearcher-dumpcenter/
     state: absent
  - name: unzip tsearcher-dumpcenter.tar.gz
    unarchive:
     src: /tmp/tsearcher-dumpcenter.tar.gz
     dest: /tmp/
     remote_src: yes
  - name: synchronize jars in tsearcher-dumpcenter
    synchronize:
      src: /tmp/tsearcher-dumpcenter/
      dest: /home/admin/terminator_builder/sharelib/tsearcher-dumpcenter
      delete: yes
    delegate_to: "{{ inventory_hostname }}"
  - name: set owner admin
    file:
     path: /home/admin/terminator_builder/sharelib/tsearcher-dumpcenter
     owner: admin
     group: admin
     recurse: yes
  #- name: synchronize jars
  #  synchronize:
  #   src: /tmp/tsearcher-dumpcenter/
  #   dest: /home/admin/terminator_builder/sharelib/tsearcher-dumpcenter
  #   delete: yes
  #- file: 
  #   path: /home/admin/terminator_builder/sharelib/tsearcher-dumpcenter
  #   owner: admin
  #   recurse: yes
  #- file:
  #   path: /tmp/tsearcher-dumpcenter
  #   state: absent
