---
- name: build tis-console
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: git pull
    git:
     repo: 'git@github.com:baisui1981/tis.git'
     dest: /opt/data/tiscode/tis
     version: "{{git_branch}}"
  
  - name: copy compile shell script
    copy: src=compile.sh dest=/opt/data/tiscode/tis mode=u+rwx

  - name: compile and package
    command: ./compile.sh {{runtime}} tis
    args:
     chdir: /opt/data/tiscode/tis

- name: synchronize jars
  hosts: "tis-console"
  become: yes
  become_method: sudo
  tags: deploy
  tasks:
  - name: copy tar
    copy:
     src: /opt/data/tiscode/tis/{{item}}
     dest: /tmp/
    with_items:
     - "tis.tar.gz"
  - name: delete history tar.gz
    file:
      path: /tmp/tis
      state: absent
  - name: untar
    unarchive:
     src: /tmp/tis.tar.gz
     dest: /tmp/
     remote_src: yes
  - name: synchroniz tis
    shell: |
       rsync --delete -r /tmp/tis/ /opt/app/spring-boot/tis
       exit 0
  - name: copy config.properties
    template:
     src: template/{{item}}.j2
     dest: /opt/app/spring-boot/tis/conf/tis-web-config/{{item}}
    with_items:
     - "config.properties"
     - "hdfs-site.xml"
  - name: path owner set
    file:
     path: /opt/app/spring-boot/tis
     owner: spring-boot
     group: spring-boot
     recurse: yes
