---

- name: compile tis src tar package
  vars_files:
   - vars.yml
  hosts: localhost      
  roles:
   - role: compile
   - role: tis-incr
  tags:
    - package
    
- import_playbook: install_struct.yml
  

