---
- name: init solrhome
  hosts: "solr7.6"
  become: yes
  become_method: sudo
  #vars_prompt: 
  #  - name: hosts
  #    prompt: 'hosts you want to synchronize[prod,solr5-kr]:'
  #    default: solr5-kr
  #    private: no
  tags: deploy
  tasks:
  - name: add spring-boot user
    user:
      name: spring-boot
  - file:
      path: /opt/data/solrhome
      owner: spring-boot  
      state: directory
  - name: copy solr.xml 
    copy:
     src: /opt/data/tiscode/solrhome/{{item}}
     dest: /opt/data/solrhome/
     owner: spring-boot
    with_items:
     - "solr.xml"
  - name: copy app.info
    copy:
     src: /opt/data/tiscode/solrhome/{{item}}
     dest: /opt/app/
     owner: spring-boot
    with_items:
     - "app.info"

#- name: build deploy
#  hosts: "buildtask"
#  become: yes
#  become_method: sudo
#  tasks:
#  - name: add admin user
#    user:
#      name: admin
#  - copy:
#      src: /home/admin/terminator_builder.tar
#      dest: /home/admin/ 
