
- name: deploy tis_console
  vars_files:
   - vars.yml
  hosts: tis-console
  tasks:
  - shell: 'ls {{tis_release_dir}}'
    ignore_errors: True
    register: release_files
  - debug: var=release_files
  - include_role:
     name: console
    when: release_files.stdout.find('tis.tar.gz') != -1
   
- name: deploy assemble
  vars_files:
   - vars.yml
  hosts: assemble
  tasks:
  - shell: 'ls {{tis_release_dir}}'
    ignore_errors: True
    register: release_files
  - include_role:
     name: assemble
    when: release_files.stdout.find('tis-assemble.tar.gz') != -1

- name: deploy solr-core
  hosts: solr7.6
  vars_files:
   - vars.yml
  tasks:
  - shell: 'ls {{tis_release_dir}}'
    ignore_errors: True
    register: release_files
  - include_role:
     name: solr_core
    when: release_files.stdout.find('solr.tar.gz') != -1