
- name: get file in tis_release_dir
  vars_files:
   - vars.yml
  shell: ls {{tis_release_dir}}
  ignore_errors: True
  register: release_files

- name: deploy tis_console
  vars_files:
   - vars.yml
  hosts: tis-console
  roles:
   - role: console
  when: release_files.stdout.find('tis.tar.gz') != -1
   
- name: deploy assemble
  vars_files:
   - vars.yml
  hosts: assemble
  roles:
   - role: assemble
  when: release_files.stdout.find('tis-assemble.tar.gz') != -1

- name: deploy solr-core
  vars_files:
   - vars.yml
  hosts: solr7.6
  roles:
   - role: solr_core
  when: release_files.stdout.find('solr.tar.gz') != -1