---
- name: start zookeeper
  vars_files:
    - vars.yml
  hosts: zookeeper
  tasks:
  - command: ./zkServer.sh start
    become: yes
    become_user: zookeeper
    ignore_errors: yes
    args:
      chdir: "{{zk_install_dir}}/bin"
  - command: sleep 5
    ignore_errors: yes
  - service: name=crond state=started enabled=yes
  tags:
    - zk

- name: start hdfs
  vars_files:
    - vars.yml
  hosts: hadoop-hdfs-namenode
  tasks:
  - command: ./start-dfs.sh
    become: yes
    become_user: "{{hadoop_user}}"
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"
  - command: sleep 15
    ignore_errors: yes

- name: start yarn
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./start-yarn.sh
    become: yes
    become_user: "{{hadoop_user}}"
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"
  - command: sleep 10
    ignore_errors: yes

- name: start thriftserver
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./start-thriftserver.sh --master yarn --deploy-mode client --name thriftserver --driver-java-options "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8101"
    become: yes
   # become_user: hadoop
    become_user: "{{hadoop_user}}"
    ignore_errors: yes
    args:
      chdir: "/opt/app/spark/sbin"
    when: need_install_spark and need_install_spark_shuffle
  - command: sleep 5
    ignore_errors: yes
  tags:
    - tserver



- name: start tis
  vars_files:
    - vars.yml
  hosts: solr,tis-console,assemble
  tasks:
  - command: ./tis restart -force
    become: yes
    become_user: "{{tis_user}}"
    args:
      chdir: "{{tis_app_dir}}/"
  - command: sleep 10
    ignore_errors: yes
  tags:
    - tjs

# must start console first
#- name: start tis-console
#  vars_files:
#    - vars.yml
#  hosts: tis-console
#  tasks:
#  - command: ./tis start
#    become: yes
#    become_user: tis
#    ignore_errors: yes
#    args:
#      chdir: "/opt/app/spring-boot/bin"
#  - command: sleep 5
#    ignore_errors: yes
#
#- name: start tis-assemble
#  vars_files:
#    - vars.yml
#  hosts: assemble
#  tasks:
#  - command: ./tis start
#    become: yes
#    become_user: tis
#    ignore_errors: yes
#    args:
#      chdir: "/opt/app/spring-boot/bin"