---
- name: start zookeeper
  vars_files:
    - vars.yml
  hosts: zookeeper
  tasks:
  - command: ./zkServer.sh start
    become: yes
    become_user: zookeeper
    ignore_errors: yes
    args:
      chdir: "/opt/app/zookeeper-3.4.14/bin"
  - command: sleep 5
    ignore_errors: yes

- name: start hdfs
  vars_files:
    - vars.yml
  hosts: hadoop-hdfs-namenode
  tasks:
  - command: ./start-dfs.sh
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"
  - command: sleep 15
    ignore_errors: yes

- name: start yarn
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./start-yarn.sh
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"
  - command: sleep 10
    ignore_errors: yes

- name: start thriftserver
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./start-thriftserver.sh --master yarn --deploy-mode client --name thriftserver
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/spark/sbin"
    when: need_install_spark and need_install_spark_shuffle
  - command: sleep 5
    ignore_errors: yes

- name: start solr
  vars_files:
    - vars.yml
  hosts: solr7.6
  tasks:
  - command: ./solr start
    become: yes
    become_user: solr
    ignore_errors: yes
    args:
      chdir: "/opt/app/spring-boot/solr"
  - command: sleep 10
    ignore_errors: yes

# must start console first
- name: start tis-console
  vars_files:
    - vars.yml
  hosts: tis-console
  tasks:
  - command: ./tis start
    become: yes
    become_user: tis
    ignore_errors: yes
    args:
      chdir: "/opt/app/spring-boot/bin"
  - command: sleep 5
    ignore_errors: yes

- name: start tis-assemble
  vars_files:
    - vars.yml
  hosts: assemble
  tasks:
  - command: ./tis start
    become: yes
    become_user: tis
    ignore_errors: yes
    args:
      chdir: "/opt/app/spring-boot/bin"