---
- name: stop tis
  vars_files:
    - vars.yml
  hosts: tis-console,assemble
  tasks:
  - command: ./tis stop -p 8080
    become: yes
    become_user: tis
    ignore_errors: yes
    args:
      chdir: "/opt/app/spring-boot/bin"

- name: stop solr
  vars_files:
    - vars.yml
  hosts: solr7.6
  tasks:
  - command: ./solr stop -p 8080
    become: yes
    become_user: solr
    ignore_errors: yes
    args:
      chdir: "/opt/app/spring-boot/solr"

- name: stop thriftserver
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./stop-thriftserver.sh
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/spark/sbin"
    when: need_install_spark and need_install_spark_shuffle

- name: stop yarn
  vars_files:
    - vars.yml
  hosts: hadoop-yarn-resource-manager
  tasks:
  - command: ./stop-yarn.sh
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"

- name: stop hdfs
  vars_files:
    - vars.yml
  hosts: hadoop-hdfs-namenode
  tasks:
  - command: ./stop-dfs.sh
    become: yes
    become_user: hadoop
    ignore_errors: yes
    args:
      chdir: "/opt/app/hadoop/sbin"

- name: stop zookeeper
  vars_files:
    - vars.yml
  hosts: zookeeper
  tasks:
  - command: ./zkServer.sh stop
    become: yes
    become_user: zookeeper
    ignore_errors: yes
    args:
      chdir: "/opt/app/zookeeper-3.4.14/bin"
