---
- name: deploy build task pakcage
  become: yes
  become_method: sudo
  hosts: "buildtask-overseer,buildtask-worker"
  tasks:
  - name: add admin user
    user:
     name: admin
#     group: admin
  - name: remove old file
    file:
      path: /tmp/{{item}}
      state: absent
    with_items:
     - "terminator_builder"
     - "terminator_builder.tar"
  - name: synchronize tar
    copy:
     src: /home/admin/terminator_builder.tar
     dest: /tmp/
  - name: untar 
    unarchive:
     src: /tmp/terminator_builder.tar
     dest: /tmp/
     remote_src: yes
  - name: synchronize files
    synchronize:
      src: /tmp/terminator_builder/
      dest: /home/admin/terminator_builder
      delete: yes
    delegate_to: "{{ inventory_hostname }}"
  - name: create dir tis-web-config
    file:
      path: /home/admin/terminator_builder/conf/tis-web-config
      state: directory   
  - name: copy task_tracker.xml
    template:
      src: template/{{item.name}}.j2
      dest: /home/admin/terminator_builder/{{item.dir}}{{item.name}}
    with_items:
      - {name: "task_tracker.xml" , dir: "conf/"}
      - {name: "hdfs-site.xml" , dir: "conf/tis-web-config/"}
      - {name: "config.properties" , dir: "conf/tis-web-config/"}    
  - name: set owner
    file:
     path: /home/admin/terminator_builder
     owner: admin
     group: admin
     recurse: yes
    
     
