---
- name: Play the template module
  hosts: localhost
  vars:
    dynamic_word: "World"
  tasks:
   - name: generation the hello_world.txt file
     template:
       src: template/config.properties.j2
       dest: /tmp/hello_world.txt

   - name: show file context
     command: cat /tmp/hello_world.txt
     register: result

   - name: print stdout
     debug:
       msg: ""
