#app_local_dir_name: "{{tis_release_dir_name}}"

flink_dist_dir: "{{src_dir}}/flink-dist/target/flink-{{git_branch}}-bin/flink-{{git_branch}}"
src_dir: "{{src_root}}/{{app_local_dir_name}}"

tis_flink_dist_dir: "{{ tis_release_dir }}/{{tis_release_dir_name}}/{{tis_pkg_version}}/{{app_local_dir_name}}"



