---
# tasks file for collector
#  - file:
#     path: /opt/data/spring-boot
#     owner: "{{tis_user}}"
#     state: directory

#  - file:
#     path: /opt/data/flume
#     owner: "{{tis_user}}"
#     state: directory

  - name: copy tis-collect
    copy:
     src: "{{tis_release_dir}}/{{tis_release_dir_name}}/{{item}}"
     dest: /tmp/
    with_items:
     - "tis-collect.tar.gz"

  - name: delete history tar.gz
    file:
      path: /tmp/tis-collect
      state: absent

  - name: untar
    unarchive:
      src: /tmp/tis-collect.tar.gz
      dest: /tmp/
      remote_src: yes


  - name: synchroniz collector
    synchronize:
       src: /tmp/tis-collect/
       dest: "{{app_dir}}/tis-collect"
       delete: yes
       recursive: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: mkdir tis-web-config
    file:
     path: "{{app_dir}}/tis-collect/conf/tis-web-config"
     state: directory


  - name: copy config.properties
    template:
     src: template/{{item}}.j2
     dest: "{{app_dir}}/tis-collect/conf/tis-web-config/{{item}}"
    with_items:
     - "config.properties"

  - name: path owner set
    file:
     path: "{{item}}"
     owner: "{{tis_user}}"
     recurse: yes
    with_items:
     - "{{app_dir}}/tis-collect"
 #    - "/opt/data/spring-boot"