---
- name: restart zookeeper
  command: ./zkServer.sh restart
  become: yes
  become_user: zookeeper
  ignore_errors: yes
  args:
    chdir: "{{zk_install_dir}}/bin"
- name: sleep 5
  command: sleep 5
  ignore_errors: yes