---
- name: restart zookeeper
  - command: ./zkServer.sh restart
    become: yes
    become_user: zookeeper
    ignore_errors: yes
    args:
      chdir: "/opt/app/zookeeper-3.4.14/bin"
  - command: sleep 5
    ignore_errors: yes