---
# tasks file for solr_core
  - group: name=solr
  - name: add user solr
    user:
      name: solr
      group: solr
      append: yes
  - name: copy solr.tar 
    copy:
     src: "{{tis_release_dir}}/{{item}}"
     dest: /tmp/
    with_items:
     - "solr.tar.gz"
  
  - name: delete history tar.gz
    file:
      path: /tmp/solr
      state: absent
 
  - name: untar
    unarchive:
      src: /tmp/solr.tar.gz
      dest: /tmp/
      remote_src: yes
 
  - name: synchroniz solr
    synchronize:
     src: /tmp/solr/
     dest: /opt/app/spring-boot/solr
     delete: yes
     recursive: yes
    delegate_to: "{{ inventory_hostname }}"
    notify: restart solr
  
  - name: create log dir
    file: "{{solr_log_dir}}"
    state: directory
    owner: solr
    
  - name: copy config.properties
    template:
     src: template/{{item}}.j2
     dest: "{{solr_app_dir}}/conf/tis-web-config/{{item}}"
    with_items:
     - "config.properties"
     - "hdfs-site.xml"
    notify: restart solr
    
  - name: copy solr start script
    template:
     src: ./template/{{item}}.j2
     dest: "{{solr_app_dir}}/{{item}}"
    with_items:
     - "solr"
     - "solr.in.sh"
    notify: restart solr
  
  - name: set solr script mode
    file:
     path: "{{solr_app_dir}}/solr"
     mode: '+x'
    notify: restart solr
    
  - name: path owner set
    file:
     path: "{{solr_app_dir}}"
     owner: solr
     group: solr
     recurse: yes