---
# tasks file for compile

  - name: create docker context dir {{docker_context_dir}}/{{tis_incr_name}}
    file:
      path: '{{docker_context_dir}}/{{tis_incr_name}}'
      state: directory

  - name: copy {{tis_incr_name}} to docker context dir
    file:
     src: '{{tis_release_dir}}/{{item.tar_name}}'
     path: '{{docker_context_dir}}/{{item.app}}/{{item.tar_name}}'
     state: hard
    with_items:
      - {app : "{{tis_incr_name}}" ,tar_name: "{{tis_incr_tar_name}}"}

  - name : copy run.sh to docker context dir
    template:
     src: template/run.sh.j2
     dest: '{{docker_context_dir}}/{{tis_incr_name}}/run.sh'

  - name : copy Dockerfile to docker context dir {{docker_context_dir}}/{{tis_incr_name}}/
    copy: src="files/Dockerfile" dest="{{docker_context_dir}}/{{tis_incr_name}}/"

  - name : docker image {{tis_incr_name}} build
    command: docker build -t tis/tis-incr -f ./Dockerfile .
    args:
      chdir: "{{docker_context_dir}}/{{tis_incr_name}}"
     
     