---
# task file for initialize OS
# install common software
# enable ntpd
# disable firewalld, selinux

  - name: install epel packages
    yum:
      name: epel-release

  - name: install basic packages
    yum:
      name: "{{ basic_packages }}"
    vars:
      basic_packages:
      - lsof
      - ntp
      - unzip
      - rsync
      - nmap.x86_64
      - vim
      - lrzsz
      - bash-completion
      - net-tools
      - sysstat
      - iotop
      - iftop
      - wget

  - name: enable ntpd service
    service: name=ntpd state=started enabled=yes

  - name: disable firewalld service
    service: name=firewalld state=stopped enabled=no

  - name: get selinux status
    shell: getenforce
    register: old_selinux_stat
  - name: disable selinux
    shell: setenforce 0
    when: old_selinux_stat.stdout != "Disabled"
  - name: disable selinux forever
    lineinfile:
      dest: /etc/selinux/config
      regexp: '^SELINUX=enforcing'
      line: 'SELINUX=disabled'
      state: present

  # make sure /opt use the largest partition of disk
  - name: check largest partition point
    shell: "lsblk | awk '{if ($7) print $4 \" \" $7}' | sort -h | tail -n 1 | awk '{print $2}'"
    register: max_partition_point
  # if it's already a symbol link to directory, nothing will happedn
  - name: make sure /opt exists
    file:
      path: /opt
      state: directory
  - name: read /opt status
    stat:
      path: /opt
    register: opt_old_stat
  - name: check if /opt is empty
    shell: "du -h /opt --max-depth=0 | awk '{print $1}'"
    register: opt_directory_usage
  # the when conditon make sure symbol link be created under one of the following conditions:
  # 1. /opt is a link, and it's not linked to the largest partition
  # 2. /opt is not a link, and it's empty, and the largest partition is not /, and the largest partition is not /opt
  - name: create symbol link when /opt is not linked to largest partition point and /opt is empty
    file:
      src: "{{ max_partition_point.stdout }}"
      name: /opt
      state: link
      force: yes
    when:
      (not opt_old_stat.stat.islnk or max_partition_point.stdout != opt_old_stat.stat.lnk_source) and
      max_partition_point.stdout[0] == '/' and
      max_partition_point.stdout != '/' and
      max_partition_point.stdout != '/opt' and
      opt_directory_usage.stdout == '0'

  # prepare directories
  - name: make /opt/app directory
    file:
      path: /opt/{{ item }}
      state: directory
      recurse: yes
      mode: '0777'
    with_items:
      - app
      - data


  - name: init hostname
    hostname:
      name: "{{ inventory_hostname }}"
      use: redhat

  # use with_inventory_hostnames to set all hosts to /etc/hosts
  - name: set hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: "^.*? {{ item }}$"
      line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
      state: present
      create: yes
    with_inventory_hostnames: all
