---
# defaults file for compile
#git_src: git@code.aliyun.com:qlangtech/tis-solr.git

git_src: https://code.aliyun.com/qlangtech/tis-solr.git
app_local_dir_name: tis
#example: /opt/data/tiscode/tis
src_dir: "{{src_root}}/{{app_local_dir_name}}"
git_branch: master
target_file_pattern: "*.tar.gz"



mvn_pkg_name: apache-maven-3.3.3
mvn_parent_dir: /opt/app
mvn_home: '{{mvn_parent_dir}}/{{mvn_pkg_name}}'
appname: all
mvn_zip_package_name: '{{mvn_pkg_name}}.zip'
mvn_local_repo: /opt/data/mvn_repository