---
# defaults file for compile
git_src: git@github.com:baisui1981/tis-solr.git
src_dir: /opt/data/tiscode/tis
mvn_pkg_name: apache-maven-3.3.3
mvn_parent_dir: /opt/app
mvn_home: '{{mvn_parent_dir}}/{{mvn_pkg_name}}'
appname: all
mvn_zip_package_name: '{{mvn_pkg_name}}.zip'
mvn_local_repo: /opt/data/mvn_repository