---
- name: empty {{tis_data_dir}}/libs/tis-ibatis
  file:
    path: "{{tis_data_dir}}/libs/tis-ibatis"
    state: absent

- name: make empty dir of {{tis_data_dir}}/libs/tis-ibatis
  file:
    path: "{{tis_data_dir}}/libs/tis-ibatis"
    state: directory

- name: install tis-ibatis dependencies
  unarchive:
    src: "{{ tis_release_dir }}/{{tis_ibatis_gz_file_name}}"
    dest: "{{tis_data_dir}}/libs/tis-ibatis/"

#- name: clean {{tis_scala_compiler_dependencies_dir_name}}
#  file:
#    path: "{{tis_data_dir}}/libs/{{tis_scala_compiler_dependencies_dir_name}}"
#    state: absent
#
#- name: install {{tis_scala_compiler_dependencies_dir_name}}
#  unarchive:
#    src: "{{ tis_release_dir }}/{{tis_release_dir_name}}/{{tis_scala_compiler_dependencies_gz_file_name}}"
#    dest: "{{tis_data_dir}}/libs/"