---
# tasks file for console
- name: git pull {{tis_local_cfg_git_repository}}@master '{{tis_data_dir}}/cfg_repo'
  git:
    repo: '{{tis_local_cfg_git_repository}}'
    dest: '{{tis_data_dir}}/cfg_repo'
    version: 'master'
    force: yes
    accept_hostkey: yes


- name: copy tar
  copy:
     src: "{{tis_release_dir}}/{{tis_release_dir_name}}/{{item}}"
     dest: /tmp/
  with_items:
     - "tis.tar.gz"

- name: copy plugins from "{{tis_release_dir}}/tis-plugin/"
  synchronize:
    src: "{{tis_release_dir}}/tis-plugin/"
    dest: "{{tis_data_dir}}/libs/plugins/"
    delete: yes
  notify: restart tis-console

- name: delete history tis.tar.gz
  file:
      path: /tmp/tis
      state: absent
- name: untar
  unarchive:
     src: /tmp/tis.tar.gz
     dest: /tmp/
     remote_src: yes

- name: synchroniz tis
  synchronize:
     src: /tmp/tis/
     dest: /opt/app/spring-boot/{{tis_app_name}}
     delete: yes
     recursive: yes
  delegate_to: "{{ inventory_hostname }}"
  notify: restart tis-console
  
#- name: copy config.properties
#  template:
#     src: template/hdfs-site-proxy.xml.j2
#     dest: /opt/app/spring-boot/tis/conf/tis-web-config/hdfs-site.xml

- name: copy config.properties
  template:
     src: template/{{item}}.j2
     dest: "/opt/app/spring-boot/{{tis_app_name}}/conf/tis-web-config/{{item}}"
  with_items:
     - "config.properties"
     - "yarn-site.xml"
  notify: restart tis-console
  
- name: path owner set
  file:
     path: /opt/app/spring-boot/{{tis_app_name}}
     owner: "{{tis_user}}"
     group: "{{tis_user}}"
     recurse: yes

- name: set tis dir mode
  file:
    path: "{{tis_data_dir}}"
    owner: "{{tis_user}}"
    group: "{{tis_user}}"
    mode: '0777'
    recurse: yes