---
# tasks file for console
- name: copy tar
  copy:
     src: "{{tis_release_dir}}/{{item}}"
     dest: /tmp/
  with_items:
     - "tis.tar.gz"
- name: delete history tis.tar.gz
  file:
      path: /tmp/tis
      state: absent
- name: untar
  unarchive:
     src: /tmp/tis.tar.gz
     dest: /tmp/
     remote_src: yes
- name: synchroniz tis
  synchronize:
     src: /tmp/tis/
     dest: /opt/app/spring-boot/{{tis_app_name}}
     delete: yes
     recursive: yes
  delegate_to: "{{ inventory_hostname }}"
  notify: restart tis-console
  
- name: copy config.properties
  template:
     src: template/hdfs-site-proxy.xml.j2
     dest: /opt/app/spring-boot/tis/conf/tis-web-config/hdfs-site.xml

- name: copy config.properties
  template:
     src: template/{{item}}.j2
     dest: /opt/app/spring-boot/tis/conf/tis-web-config/{{item}}
  with_items:
     - "config.properties"
     - "yarn-site.xml"
  notify: restart tis-console
  
- name: path owner set
  file:
     path: /opt/app/spring-boot/{{tis_app_name}}
     owner: tis
     group: tis
     recurse: yes