---
# tasks file for solrhome
  - group: name=solr
  - name: add user solr
    user:
      name: solr
      group: solr
  
  - file:
      path: /opt/data/solrhome
      owner: solr  
      state: directory
  
#  - name: copy solr.xml
#    copy:
#     src: ./files/solrhome/{{item}}
#     dest: /opt/data/solrhome/
#     owner: solr
#    with_items:
#     - "solr.xml"

  - name: copy solr.xml to '/opt/data/solrhome/'
    template:
      src: './files/solrhome/{{item}}'
      dest: '/opt/data/solrhome/'
    with_items:
      - "solr.xml"


  - name: copy app.info
    copy:
     src: ./files/solrhome/{{item}}
     dest: /opt/app/
     owner: solr
    with_items:
     - "app.info"