tis_log_dir_name: "logs"
tis_log_dir: "/opt/{{tis_log_dir_name}}/tis"
uber_pkg: no
tis_java_mem: "-Xms2G -Xmx3G"

relative_root_dir: "{{app_dir}}"
app_home: "{{app_dir}}"
tis_server_port: "8080"

uber_docker_pkg : no
