---
# tasks file for taskcenter
  
  - group: name={{ hadoop_group}} state=present
  - user: name={{ hadoop_user }} comment="Hadoop" group={{ hadoop_group}} shell=/bin/bash
  
  - name: remove old file
    file:
      path: /tmp/{{item}}
      state: absent
    with_items:
     - "{{hadoop_dir_name}}"
      
  - name: get hadoop tar from http repository
    get_url:
     url: "{{release_repository}}/{{item}}"
     dest: "/tmp/{{item}}"
    with_items:
     - "{{hadoop_dir_name}}.tar.gz"
 
  - name: untar 
    unarchive:
     src: '/tmp/{{hadoop_dir_name}}.tar.gz'
     dest: /tmp/
     remote_src: yes
     
  - name: synchronize files
    synchronize:
      src: '/tmp/{{hadoop_dir_name}}'
      dest: '{{hadoop_parent_dir}}'
      delete: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: create config dir 
    file:
      path: '{{hadoop_cfg_dir}}'
      state: directory
      
  - name: copy config files
    template:
      src: 'template/{{item.name}}.j2'
      dest: '{{hadoop_cfg_dir}}/{{item.name}}'
    with_items:
      - {name: "hdfs-site.xml" }
      - {name: "yarn-site.xml"}
      - {name: "config.properties"}
      
  - name: "Build hosts file yarn master"
    lineinfile: dest=/etc/hosts  line="{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}" state=present create=yes
    with_items: "{{groups['hadoop-yarn-resource-manager']}}"
    
  - name: "Build hosts file yarn slaver"
    lineinfile: dest=/etc/hosts  line="{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}" state=present create=yes
    with_items: "{{groups['hadoop-yarn']}}"
  
  - lineinfile: 
     dest: "{{hadoop_cfg_dir}}/hadoop-env.sh"
     regexp: "^export JAVA_HOME"
     line: "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64"
     state: present
  
  - name: set nodemanager resourcemanager max heap size
    lineinfile: 
      dest: "{{hadoop_cfg_dir}}/hadoop-env.sh"
      regexp: "^export {{item}}"
      line: "export {{item}}={{YARN_RESOURCE_NODE_MANAGER_HEAPSIZE}}"
      state: present
    with_items:
     - "YARN_RESOURCEMANAGER_HEAPSIZE"
     - "YARN_NODEMANAGER_HEAPSIZE"
  
  - name: set owner
    file:
     path: "{{hadoop_dir}}"
     owner: "{{hadoop_user}}"
     group: "{{hadoop_group}}"
     recurse: yes