---
# tasks file for taskcenter
  - name: add yarn user
    user:
     name: yarn
  
  - name: remove old file
    file:
      path: /tmp/{{item}}
      state: absent
    with_items:
     - "{{hadoop_dir_name}}"
     - "{{hadoop_dir_name}}.tar.gz"
      
  - name: synchronize tar
    get_url:
     url: "{{release_repository}}/{{item}}"
     dest: "/tmp/{{item}}"
    with_items:
     - "{{hadoop_dir_name}}.tar.gz"
 
  - name: untar 
    unarchive:
     src: '/tmp/{{hadoop_dir_name}}.tar.gz'
     dest: /tmp/
     remote_src: yes
     
  - name: synchronize files
    synchronize:
      src: '/tmp/{{hadoop_dir_name}}'
      dest: '{{hadoop_parent_dir}}'
      delete: yes
    delegate_to: "{{ inventory_hostname }}"

  - name: create config dir 
    file:
      path: '{{hadoop_cfg_dir}}'
      state: directory
      
  - name: copy config files
    template:
      src: 'template/{{item.name}}.j2'
      dest: '{{hadoop_cfg_dir}}/{{item.name}}'
    with_items:
      - {name: "hdfs-site.xml" }
      - {name: "yarn-site.xml"}
      - {name: "config.properties"}
      
  - name: set owner
    file:
     path: '{{hadoop_dir}}'
     owner: yarn
     group: yarn
     recurse: yes