---
# tasks file for compile
  - name: judge maven is deployed
    shell: ls {{mvn_home}}/conf/setting.xml
    ignore_errors: True
    register: ismvndeploy
    
  - name: make {{mvn_local_repo}} {{mvn_home}}
    file:
     path: "{{item}}"
     state: directory
    with_items:
     - "{{mvn_local_repo}}"
     - "{{mvn_home}}"
    when: ismvndeploy is failed
  
  - name: deploy maven builder
    unarchive:
      src: '{{release_repository}}/{{mvn_zip_package_name}}'
      dest: '{{mvn_parent_dir}}'
      remote_src: yes
    when: ismvndeploy is failed
  
  - name: make sh mvn mode
    file:
     path: "{{mvn_home}}/bin/mvn"
     mode: u+rwx
    when: ismvndeploy is failed
    
  - template:
     src: template/settings.xml.j2
     dest: '{{mvn_home}}/conf/settings.xml'
    when: ismvndeploy is failed
   
  - name: mkdir
    file:
     path: "{{src_dir}}"
     state: directory

  - name: git pull
    git:
     repo: '{{git_src}}'
     dest: '{{src_dir}}'
     version: '{{git_branch}}'
  
  - name: copy compile shell script
    template:
     src: template/compile.sh.j2
     dest: '{{src_dir}}/compile.sh'
     mode: u+rwx

  - name: compile and package
    command: ./compile.sh {{runtime}} {{appname}}
    args:
     chdir: "{{src_dir}}"