---
# tasks file for spring-boot
  - name: add spring-boot user
    user:
      name: spring-boot
  - name: copy springboot config
    copy:
     src: ./files/springboot/{{item}}
     dest: /opt/app/spring-boot/
     owner: spring-boot
    with_items:
     - "spring-boot.conf"
     - "env.conf"
  - name: copy spring-boot script
    copy:
     src: ./files/springboot/{{item}}
     dest: /etc/init.d/
     owner: spring-boot
    with_items:
     - "spring-boot"